# Generated by Django 4.0.4 on 2022-07-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.IntegerField(null=True),
        ),
    ]
